/**
 * Row types, written by hand rather than generated.
 *
 * The schema is small and stable, and a generated file would have to be
 * regenerated by whoever next edits supabase/schema.sql — which is a step
 * that gets skipped. These mirror supabase/schema.sql; if you change a table
 * there, change it here.
 *
 * Nullable columns are `| null`, not optional, because that is what Postgres
 * actually returns.
 */

export type Teacher = {
  id: string;
  name: string;
  is_admin: boolean;
  created_at: string;
};

export type Subject = {
  id: string;
  name: string;
  /** Which classes this subject shows up for: a Class 3 row gets EVS, a Class 7 row gets Science. */
  min_grade: number;
  max_grade: number;
  sort_order: number;
  active: boolean;
};

export type Student = {
  id: string;
  name: string;
  grade: number;
  school: string | null;
  active: boolean;
  created_by?: string | null;
  created_at?: string;
};

export type Lesson = {
  id: string;
  student_id: string;
  subject_id: string;
  teacher_id: string;
  /** "YYYY-MM-DD", local calendar. See src/lib/dates.ts. */
  taught_on: string;
  note: string | null;
  created_at: string;
};

export type Exam = {
  id: string;
  student_id: string;
  /** null = a whole-school event with no single subject (e.g. "Term 1 begins"). */
  subject_id: string | null;
  title: string | null;
  exam_date: string;
  created_by?: string | null;
  created_at?: string;
};

/** teacher_students — who teaches whom. Students themselves are tuition-wide. */
export type TeacherStudent = {
  teacher_id: string;
  student_id: string;
};

/** teacher_subjects — which subjects a teacher wants to see. Empty = see everything. */
export type TeacherSubject = {
  teacher_id: string;
  subject_id: string;
};

/**
 * attendance — whether a child turned up, one row per student per day.
 *
 * Not per teacher: whether someone was in the room is a fact about the day, not
 * about who taught them. NO ROW means "not marked yet", which is deliberately
 * different from present = false. A student nobody got round to must not be
 * counted absent.
 */
export type Attendance = {
  id: string;
  student_id: string;
  /** "YYYY-MM-DD", local calendar. See src/lib/dates.ts. */
  on_date: string;
  present: boolean;
  marked_by?: string | null;
  note?: string | null;
};

/** present · absent · not marked yet. */
export type AttendanceState = boolean | null;
